#!/usr/bin/env python3
"""Export + verify a curated AlexNet-small kernel set (mixed op types).

Runs full graph validation and copies the *first* emulated layer per op type:
  conv, relu, maxpool, matmul, add

Each bundle subdir contains:
  <node>.c / .s / .in — AtallaC, PPCI asm, full emulator image (instr + .data)
  verify.json        — cos_sim, max_diff, packets, instructions, shape

Usage (from atalla-graph/):
  python scripts/export_alexnet_kernel_bundle.py --out-bundle out/alexnet_kernels
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np
import torch

_ATALLA_GRAPH = Path(__file__).resolve().parent.parent
_REPO = _ATALLA_GRAPH.parent
for p in (_ATALLA_GRAPH, _REPO / "functional_sim"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

os.chdir(_ATALLA_GRAPH)

from run_graph import build_graph, load_model, run_validate  # noqa: E402


README = """# AlexNet-small kernel bundle

Generated by `scripts/export_alexnet_kernel_bundle.py` after a successful
`run_validate` pass. One subdirectory per *first* occurrence of:

- **conv** — im2col + tiled GEMM
- **relu**
- **maxpool**
- **matmul** — FC matmul (weight from `get_attr` + transpose in graph)
- **add** — bias add

## Files

| File | Role |
|------|------|
| `*.in` | Full loadable image for `functional_sim` (instr hex + `.data` DRAM) |
| `*.s` | PPCI / `atalla_cc` assembly for that layer |
| `*.c` | AtallaC source |
| `verify.json` | Emulator vs PyTorch reference for that layer |

Full-network validation still runs once; this bundle is for inspection / handoff.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Export verified AlexNet-small kernel artifacts")
    ap.add_argument("--out-bundle", default="out/alexnet_kernel_bundle", help="Bundle root directory")
    ap.add_argument("--work-dir", default="out/graph_bundle_work", help="Temp per-node .c/.s/.in")
    ap.add_argument("--scale", type=float, default=0.01)
    ap.add_argument(
        "--validate-inputs",
        choices=("chained", "oracle"),
        default="oracle",
        help="oracle (default): verify.json compares each kernel vs PyTorch with matched inputs.",
    )
    args = ap.parse_args()

    torch.manual_seed(42)
    np.random.seed(42)

    model, x = load_model("alexnet_small", scale=args.scale)
    gm = build_graph(model, x, verbose=True)

    bundle = Path(args.out_bundle)
    bundle.mkdir(parents=True, exist_ok=True)

    run_validate(
        gm,
        model,
        x,
        args.work_dir,
        verbose=True,
        kernel_bundle_dir=str(bundle),
        validate_inputs=args.validate_inputs,
    )

    (bundle / "README.txt").write_text(README)
    print(f"\nBundle written under {bundle.resolve()}")


if __name__ == "__main__":
    main()
